### ISSUE TITLE
CMD cloud-info-provider ?

### ISSUE THREAD

**Issue by kira2600** [enolfc/fedcloudappliance#3]
https://github.com/enolfc/fedcloudappliance/blob/2267e518315fded33221706447cd75481d0de1bb/cloud-info/cloud/Dockerfile#L20

Looks like that script does not executed in container.
And in container porpoises  I see:
```
USER       PID %CPU %MEM    VSZ   RSS TTY      STAT START   TIME COMMAND
root         1  0.1  0.4 116408 15544 ?        Ss   17:56   0:00 /usr/bin/python2 /usr/bin/supervisord -c /etc/supervisord.d/bdii.ini
root        50  0.6  0.0  13420  2016 pts/0    Ss   18:01   0:00 bash
root        65  0.0  0.0  53340  1872 pts/0    R+   18:01   0:00 ps aux
```
And in `/var/log/bdii/bdii-update.log` : `cloud-info-provider-service: error: unrecognized arguments: --os-project-name`

But if I execute that file manually, log is empty and looks like everything is working. 
Could you please describe what is normal behaviour?

**Comment by enolfc** [comment]
The `cloud-info-provider` script is called periodically by the bdii stuff, but it seems you are using an old version. Could you check which one is it? The call with --os-project-name  is no longer in the script.

**Comment by kira2600** [comment]
I have docker image_tag: 'v0.6' . I've coped it from this yaml: `https://github.com/EGI-Foundation/VMI-endorsement/blob/master/ubuntu/provisioners/appliance.yaml`
Do I need to use tag 'latest'?
