### ISSUE TITLE
improvement 

### ISSUE THREAD

**Issue by kira2600** [enolfc/fedcloudappliance#5]
https://github.com/enolfc/fedcloudappliance/blob/5103b1e403699b4dd7403f599f9110b959dbeeac/cloud-info/cloud/openstack.yaml#L12

Is it possible change from ID to name?

**Comment by enolfc** [comment]
No without changing first the cloud-info-provider, could you open an issue there? https://github.com/EGI-Foundation/cloud-info-provider
