### ISSUE TITLE
improvement

### ISSUE THREAD

**Issue by kira2600** [enolfc/fedcloudappliance#6]
https://github.com/enolfc/fedcloudappliance/blob/5103b1e403699b4dd7403f599f9110b959dbeeac/cloud-info/cloud/openstack.rc#L3

https://github.com/enolfc/fedcloudappliance/blob/5103b1e403699b4dd7403f599f9110b959dbeeac/cloud-info/cloud/openstack.rc#L5

Is it possible change from ID to name?

**Comment by enolfc** [comment]
This will take anything that keystoneauth1 accepts, so in principle you should be able to specify name.
